# Auto-label approved PRs (external reviewers only)
# --------------------------------------------------
# Adds the "Approved" label to PRs when a non-maintainer user submits an approval.
# Skips maintainers (write/maintain/admin) to highlight community reviews.
# Designed to work with forked PRs using only GITHUB_TOKEN (no PATs required).
# Fork PRs must use pull_request_review (not pull_request_target) for event security.
# Fails on API errors (except label-already-exists), so maintainers can fix problems.

name: Auto-label approved PRs (external reviewers only)

on:
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  label_on_approval:
    runs-on: ubuntu-latest
    if: >
      github.event.review.state == 'approved' &&
      github.event.pull_request.state == 'open'

    steps:
      - name: Show basic event info
        run: |
          echo "Event sender: ${{ github.event.sender.login }}"
          echo "Review author: ${{ github.event.review.user.login }}"
          echo "PR head repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "PR base repo: ${{ github.event.pull_request.base.repo.full_name }}"
          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
            echo "Note: PR head is from a fork or different repo"
          else
            echo "Note: PR head is in the same repository"
          fi

      - name: Check reviewer permissions
        id: check_permissions
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reviewer = context.payload.review.user;
            console.log(`Reviewer: ${reviewer.login}, Type: ${reviewer.type}`);
            if (reviewer.type !== 'User') {
              console.log('Non-human reviewer: Will add label');
              return 'label';
            }
            try {
              const { data: collaborator } = await github.rest.repos.getCollaboratorPermissionLevel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                username: reviewer.login
              });
              const permission = collaborator.permission;
              console.log(`User permission: ${permission}`);
              if (['read', 'triage', 'none'].includes(permission)) {
                console.log(`Will add label for ${permission} user`);
                return 'label';
              } else {
                console.log(`Will skip label for ${permission} user`);
                return 'skip';
              }
            } catch (error) {
              if (error.status === 404) {
                console.log('User is not a collaborator: Will add label');
                return 'label';
              } else {
                console.log(`Permission check error: ${error.message}`);
                return 'skip';
              }
            }
          result-encoding: string

      - name: Add "Approved" label using GitHub API
        if: ${{ steps.check_permissions.outputs.result == 'label' }}
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const prNumber = context.payload.pull_request?.number || context.issue.number;
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['Approved'],
              });
              console.log(`✅ Label added to PR #${prNumber}`);
            } catch (error) {
              if (error.status === 422) {
                console.log('ℹ️ Label already exists on this PR');
              } else {
                console.log(`❌ Failed to add label: ${error.message}`);
                throw error;
              }
            }
